### ISSUE TITLE
cnfix

### ISSUE THREAD

**Issue by nwdxlgzs** [gtf35/how-to-check-sign#1]
我参考https://www.jianshu.com/p/f60b30722760和https://www.cnblogs.com/lucktian/p/10221266.html，魔改了一下，然后代码DCC（dex2c）化，扛住了cnfix3.0

**Comment by gtf35** [comment]
居然在这里看到了 cnfix ，真的是惊讶。
cnfix 其实也没啥特殊的，可以观察 cnfix 的 apk 内部有个 smali 文件，他就是给这个 smali 植入了受害者，虽然我不知道里面做了什么手脚， jadx 读不了，但是因为逻辑过于简单，所以直接用眼睛看就行。
他没啥特殊的，甚至可以说很简陋，他就是 hook 掉了获取 apk 文件位置的 Java 层代码，至于他是如何实现的，留给您自己去学习了，因为这里不教如何用保护自己的手段做坏事。
没必要单独去防御他，面对这种初级的 hook，核心的位置判断下路径是不是 /data/app/package_name-xxxx/xxx.apk 就好了。
我这个 demo 并没有去做直接读取 apk 手动计算的相关检查，因为这里存在我无法突破掉的点。
你说的这种 hook 太过于初级了，你可观察下「太极」，您如果能实现绕过太极读取到实际的 apk，欢迎 pr

**Comment by nwdxlgzs** [comment]
https://nwdxlgzs.lanzous.com/iS9ACe318qh
您可以试试可不可以过太极。另外，apk不是/data/app/pkgname-XXXXXXX/base.apk吗。过签就会打印xml数据。

**Comment by nwdxlgzs** [comment]
我觉得不能防住，太极太强了。之所以问cnfix是因为它正好破这些检验。

**Comment by gtf35** [comment]
很抱歉，笔误，在此表示歉意。
「太极」的确很强，但是如您所见，我的这个 demo 便有两个没有通过检测。
如果仅仅是为了安全防护，我个人觉得并不一定一定要去读取到真正的 apk，去手动解析，发现被 hook 可比获取到原始地址容易多了而且足够用。
安全防护是一个整体，并不一定要去拿弱项去和强项的地方去比，这是我最近的感悟。
这个项目也是抛砖引玉，提出一些思考和启发。
ps，您不要只去关注他的重打包功能，他真正厉害的是全版本稳定 hook，并不是啥重打包，那只是副产品。用其他开源的东西也能很简单的做到，但是具备这种能力的经验丰富的开发者却很少会那么去做并且公开。

**Comment by nwdxlgzs** [comment]
天堑，应用转生这种感觉难以挡住。天堑可以过MT管理器签名检验，猪场全家桶。
