### ISSUE TITLE
傀儡术的绕过签名校验机制

### ISSUE THREAD

**Issue by Wtrwx** [gtf35/how-to-check-sign#2]
请问您对此有研究吗？
我认为他的绕过方法强于太极阴
但代码混淆了，我分析不明白。

**Comment by gtf35** [comment]
很遗憾，我没听过这个 App。但是无论如何逆向工程都应该经过原作者同意，也不应该公开讨论，
深表遗憾，抱歉。
该 issue 先关闭，有其他建议欢迎再 comment。
🙌

**Comment by gtf35** [comment]
很抱歉，草率了。
刚才查了下，这是一个类似太极的应用。
目前我查到的资料表明这个并没有开放自主创建傀儡，
如果您 App 的权益被他侵犯了的话，可以试试反射他注入的类，如果没有抛异常就是被处理了。
这种被动的处理方式其实也不错，欢迎继续 Comment 探讨

**Comment by Wtrwx** [comment]
这个app开放了创建傀儡，但由于年久失修，开发者不再维护
并且限制了使用时间，将**系统时间调至2019年10月1日**可以创建傀儡，我的app并没有被注入，但我对他强大的机制很好奇。

**Comment by gtf35** [comment]
因为我不能确定我公开的东西会不会被滥用以至于最后再祸害到我头上，所以有一些东西只能由您自己完成。
我猜测你说的强大机制应该是 hook 了文件读写，所有针对文件的校验都会被重定向到原版 apk。
别的我也母鸡了，如上文所说的，想反抗很容易，在此不再赘述。
祝您生活愉快，该 issue 先关闭，有其他建议欢迎再 comment。😉
