### ISSUE TITLE
DataInputStream 后面的很长的签名怎么生成的？

### ISSUE THREAD

**Issue by CalmCenter** [gtf35/how-to-check-sign#3]
签名校验具体是如何通过的？是我们获取的 MD5 值和 提前定义好的 MD5 字符串相同吗？

为什么 DataInputStream 后面很长的签名生成的 signatures 最终和 我提前定义好的 MD5 字符串 相同？

是 APK 中拿到了签名的某些东西吗？能否指点一下或提供一下相关资料。非常感谢 ~

**Comment by gtf35** [comment]
> 签名校验具体是如何通过的？

整个文章都是在描述是怎么通过的:)，这个需要自己去品味文章了

> 是我们获取的 MD5 值和 提前定义好的 MD5 字符串相同吗？

没错，就是这样，获取到的签名信息是固定的，只要用这个证书签名的 apk ，获取到的信息都一样，然后取 md5 做个比较就好了

> 为什么 DataInputStream 后面很长的签名生成的 signatures 最终和 我提前定义好的 MD5 字符串 相同？

因为这个 `signatures` 是根据密钥的签名算出来的，同一个密钥签出来的 apk，值都是一样的

> 是 APK 中拿到了签名的某些东西吗？

你这么理解没问题，要是实在好奇是怎么算出来的，可以查一下 “apk 签名流程” 和 “APK计算签名流程” ，我随便找了一些文章：

[应用签名（官方文档）](https://source.android.google.cn/security/apksigning?hl=zh-cn)

[APK 签名方案 v2（官方文档）](https://source.android.google.cn/security/apksigning/v2?hl=zh-cn)

[APK 签名方案 v3（官方文档）](https://source.android.google.cn/security/apksigning/v3?hl=zh-cn)

如果官方的读起来枯燥，可以看看别人写的（随便找的，需要自行辨别内容真伪）

[一篇文章看明白Android v1 & v2 签名机制](https://blog.csdn.net/freekiteyu/article/details/84849651)

补充一个获取正确签名的方法：
最简单的方式就是在判断之前抛出一个异常，内容是正确的值。
然后用正式的签名打一个 release 包，运行看异常。
因为 release 的看不到日志，所以用抛异常的方式。
网上我还见过用签名算的，也有用第三方软件获取的，但是我都觉得没有直接打印出来直接。

祝身体健康，工作顺利，学有~所成~~

**Comment by CalmCenter** [comment]
非常感谢！！！ 回复这么快

祝 身体倍棒，吃嘛嘛香，当上 CTO ，迎娶白富美，哈哈
