### ISSUE TITLE
 e

### ISSUE THREAD

**Issue by GXSZone** [gtf35/how-to-check-sign#4]

**Comment by gtf35** [comment]
这篇文章的目的是抛砖引玉，培养思维，不要局限于文中的代码。

我没用过 np 管理器，但是听过，好像是致敬 MT 的那个。

虽然没用过，不知道具体实现，但是可以猜测，既然 Application 没改，那是不是修改了 `AndroidManifest.xml` 的入口点？可不可以再检查下这个？或者针对打注入的代码打击一下？

大概思路就是这样，也是我问中提到的思路，so finally 祝你身体健康工作顺利

**Comment by gtf35** [comment]
不过大概率你见到的是基于文件系统 IO 的 Hook，那就很遗憾了，比较无解，我知道能突破这种 Hook 的方法也不多，不方便透露，而且也并非本项目开源的初衷
